### ISSUE TITLE
Does offset update?

### ISSUE THREAD

**Issue by gmglickman** [myk3y/AutoClock#2]
Nicely done. But I don't see how offset gets updated after startup(), such as when DST changes twice a year.

**Comment by myk3y** [comment]
Good point, there’s no DST on the equator (where I live)... I’ll look into that.

**Comment by myk3y** [comment]
I think I need to integrate the automation in here:
https://github.com/JChristensen/Timezone/tree/master/examples/WorldClock

**Comment by gmglickman** [comment]
As a workaround, I just check the offset shortly after 2am every night (the time when DST changes.)

**Comment by myk3y** [comment]
Good plan!

Have you forked it?
