### ISSUE TITLE
External libs description

### ISSUE THREAD

**Issue by fofrejin** [myk3y/AutoClock#3]
Where can I find this libs?
#include <TimeLib.h>
I've searched in Arduino Library Manager, but didn't find anything.

**Comment by kd8bxp** [comment]
It's in the "Time" library that can be found here: https://github.com/PaulStoffregen/Time

**Comment by myk3y** [comment]
> It's in the "Time" library that can be found here: https://github.com/PaulStoffregen/Time

Thank you. I missed his post

**Comment by kd8bxp** [comment]
Your welcome, I was just looking at some of my "old" projects, and saw the question. Glad to help.
